/* eslint-disable import/prefer-default-export */
export const FETCH_REQUESTS = "FETCH_REQUESTS";
export const FETCH_REQUESTS_FAILED = "FETCH_REQUESTS_FAILED";
export const FETCH_REQUEST_APPROVALS = "FETCH_REQUEST_APPROVALS";
export const FETCH_REQUEST_APPROVALS_FAILED = "FETCH_REQUEST_APPROVALS_FAILED";