/* export constant action types */
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


/** Error Types  */
export const SERVER_ERROR = 'SERVER_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';

/** Password Reset  */
export const RESET_PASSWORD_SENT = 'RESET_PASSWORD_SENT';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

export default {
    SIGN_UP: 'SIGN_UP',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    REVERIFY_ERROR: 'REVERIFY_ERROR',
    REVERIFY_SUCCESS: 'REVERIFY_SUCCESS',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
    VERIFY_ERROR: 'VERIFY_ERROR',
    NOTIFICATION_GET: 'NOTIFICATION_GET',
    NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE',
    NOTIFICATION_READALL: 'NOTIFICATION_READALL',
};