/* export constant action types */
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const FETCH_REQUESTS = "FETCH_REQUESTS";
export const FETCH_REQUESTS_FAILED = "FETCH_REQUESTS_FAILED";
export const FETCH_PENDING = "FETCH_PENDING";
export const FETCH_PAST = "FETCH_PAST";
export const FETCH_REQUEST_APPROVALS = "FETCH_REQUEST_APPROVALS";
export const FETCH_REQUEST_APPROVALS_FAILED = "FETCH_REQUEST_APPROVALS_FAILED";
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_ERROR = 'FETCH_LOCATIONS_ERROR';
export const REQUEST_TRIP_SUCCESS = 'REQUEST_TRIP_SUCCESS';
export const REQUEST_TRIP_ERROR = 'REQUEST_TRIP_ERROR';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS';
export const UPDATE_REQUEST_ERROR = 'UPDATE_REQUEST_ERROR';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_ERROR = 'DELETE_REQUEST_ERROR';

/** Error Types  */
export const SERVER_ERROR = 'SERVER_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';

/** Password Reset  */
export const RESET_PASSWORD_SENT = 'RESET_PASSWORD_SENT';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

/** Notifications */
export const NOTIFICATION_GET =  'NOTIFICATION_GET';
export const NOTIFICATION_UPDATE =  'NOTIFICATION_UPDATE';
export const NOTIFICATION_READALL = 'NOTIFICATION_READALL';
export const NOTIFICATION_READONE = 'NOTIFICATION_READONE';


export default {
    SIGN_UP: 'SIGN_UP',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    REVERIFY_ERROR: 'REVERIFY_ERROR',
    REVERIFY_SUCCESS: 'REVERIFY_SUCCESS',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
    VERIFY_ERROR: 'VERIFY_ERROR',

};